jwt:
  secretKey: ${JWT_SECRET_KEY}

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            # 1. PUBLIC AUTH ROUTE (Must be first)
            - id: user-auth-public
              uri: lb://UserService
              order: -1 # lesser the number higher the priority
              predicates:
                # This catches login and signup specifically
                - Path=/api/v1/user/auth/signup,/api/v1/user/auth/login , /api/v1/user/token/refreshAcessToken

              filters:
                - StripPrefix=2
                # NO Authentication filter here

            # 2. PROTECTED USER ROUTE
            - id: user-service
              uri: lb://UserService
              order: 0
              predicates:
                - Path=/api/v1/user/**
              filters:
                - StripPrefix=2
                - name: Authentication
                  args:
                    AuthenticationEnabled: true
                    AuthorizationEnabled: true

            # 3. POST SERVICE
            - id: post-service
              uri: lb://PostService
              predicates:
                - Path=/api/v1/post/**
              filters:
                - StripPrefix=2
                - AddRequestHeader=x-custom-header,Nishant
                - name: Authentication
                  args:
                    AuthenticationEnabled: true
                    AuthorizationEnabled: true

            # 4. CONNECTION SERVICE
            - id: connection-service
              uri: lb://ConnectionService
              predicates:
                - Path=/api/v1/connection/**
              filters:
                - StripPrefix=2
                - AddRequestHeader=x-custom-header,Nishant
                - name: Authentication
                  args:
                    AuthenticationEnabled: true
                    AuthorizationEnabled: true

            # 5. NOTIFICATION SERVICE
            - id: NotificationService
              uri: lb://NotificationService
              predicates:
                - Path=/api/v1/Notification/**
              filters:
                - StripPrefix=2
                - AddRequestHeader=x-custom-header,Nishant
                - name: Authentication
                  args:
                    AuthenticationEnabled: true
                    AuthorizationEnabled: true

            # 6. UPLOADER SERVICE
            - id: UploaderService
              uri: lb://UploaderService
              predicates:
                - Path=/api/v1/upload/**
              filters:
                - StripPrefix=2
                - AddRequestHeader=x-custom-header,Nishant
                - name: Authentication
                  args:
                    AuthenticationEnabled: true
                    AuthorizationEnabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
#      defaultZone: http://localhost:8761/eureka

server:
  port: 6085
