### Db Configuration (Parameterized)
spring.datasource.url=jdbc:mysql://mysql:3306/post_service_db

# eureka config
# Eureka Client Discovery Config
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka

# ===================================================================
# Kafka Consumer & Producer Configuration
# ===================================================================
spring.kafka.bootstrap-servers=kafka:29092