
# Database Configuration (Parameterized)
#for using docker - #jdbc:mysql://mysql:3306/your_db
spring.datasource.url=jdbc:mysql://mysql:3306/user_service_db

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#token expiry time
jwt.refresh-token-expiry-days=7
jwt.access-token-expiry-minutes=180

# Eureka Client Discovery Config
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka