spring.application.name=ConnectionService

#setting the server port
server.port = 9040
#setting the context path
server.servlet.context-path = /connection

# Neo4j Parameterized Core Configurations
#spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

## Eureka Discovery Client Mapping
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
