package com.Nishant.LinkedIn_Mini.NotificationService.Entity;
import com.Nishant.LinkedIn_Mini.NotificationService.Constant.NotificationStatus;
import com.nishant.linkedinmini.common.contracts.Constants.DeliveryChannel;
import com.nishant.linkedinmini.common.contracts.Constants.NotificationEventType;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(
        name = "notifications",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_notification_id",
                        columnNames = "notification_id"
                )
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class NotificationEntity{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique identifier generated by the producer.
     * Used for idempotency and tracking.
     */
    @Column(name = "notification_id", nullable = false, unique = true)
    private UUID notificationId;

    /**
     * POST_CREATED
     * POST_LIKED
     * CONNECTION_REQUEST
     * etc.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private NotificationEventType eventType;

    /**
     * User who will receive the notification.
     */
    @Column(nullable = false)
    private Long recipientUserId;

    @Column(nullable = false)
    private String recipientEmail;

    /**
     * EMAIL
     * SMS
     * PUSH
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private DeliveryChannel deliveryChannel;

    /**
     * PENDING
     * PROCESSING
     * SENT
     * FAILED
     * RETRYING
     * DEAD_LETTER
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private NotificationStatus status;

    @Column(nullable = false)
    private Integer retryCount;

    @Column(length = 2000)
    private String errorMessage;

    private String subject;

    /**
     * Name of the template used
     * Example:
     * post-created
     * post-liked
     * connection-request
     */
    private String templateName;

    /**
     * JSON payload used to render the template.
     *
     * Example:
     * {
     *   "authorName":"Nishant",
     *   "postId":101
     * }
     */
    @Lob
    @Column(columnDefinition = "JSON")
    private String payload;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    private LocalDateTime sentAt;

    @PrePersist
    public void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();

        if (retryCount == null) {
            retryCount = 0;
        }

        if (status == null) {
            status = NotificationStatus.PENDING;
        }
    }

    @PreUpdate
    public void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
