name: LinkedIn Mini CI

on:
  push:
    branches:
      - feature/CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Project
        run: ./build-service.sh discovery-service docker

      - name: Build Discovery Service Docker Image
        run: |
          docker build \
            -t linkedinmini/discovery-service:latest \
            -f discovery-service/Dockerfile .